default: &default
  adapter: postgresql
  encoding: unicode
  username: EFernandes
  host: localhost

development:
  <<: *default
  database: saaslike_development

test:
  <<: *default
  database: saaslike_test

# production:
#   <<: *default
#   database: saaslike_production
#   username: saaslike
#   password: <%= ENV['SAASLIKE_DATABASE_PASSWORD'] %>
